### ISSUE TITLE
Bump the Catch version

### ISSUE THREAD

**Issue by msm-code** [CERT-Polska/ursadb#189]
Ursadb tests don't build with a new glibc version:

```
In file included from /nix/store/4pqv2mwdn88h7xvsm7a5zplrd8sxzvw0-glibc-2.35-163-dev/include/signal.h:328,
                 from /build/source/extern/./catch/Catch.h:4811,
                 from /build/source/src/Tests.cpp:8:
/build/source/extern/./catch/Catch.h:7441:45: error: size of array 'altStackMem' is not an integral constant-expression
 7441 |     char FatalConditionHandler::altStackMem[SIGSTKSZ] = {};
```

Another, similar issue: https://github.com/doctest/doctest/issues/473

We should bump the Catch version and this will hopefully resolve this problem.

How to reproduce:

Certainly building ursadb_test in a modern nix derivation causes the build to fail. But any build with glibc-2.35 (or maybe even a bit older) should cause the build to fail.

**Comment by msm-code** [comment]
Fixed with #192
